language: java
jdk:
  - openjdk15
before_install:
  - chmod +x gradlew
services:
  - docker
git:
  depth: false
# safelist
branches:
  only:
    - alert
    - auth
    - location
    - master

script: ./gradlew clean install
