server:
  port: ${PORT:9000}
  user-url-email : ${user_url_email}

spring:
  kafka:
    bootstrap-servers: ${kafka_server}
    consumer:
      group-id: ${kafka_groupId}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${kafka_username}" password="${kafka_password}";
    template:
      default-topic: ${kafka_topic}
  mail:
    host: ${smtp_host}
    port: ${smtp_port}
    username: ${email}
    password: ${password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
