spring:
  kafka:
    bootstrap-servers: ${CLOUDKARAFKA_BROKERS:tricycle-01.srvs.cloudkafka.com:9094, tricycle-02.srvs.cloudkafka.com:9094, tricycle-03.srvs.cloudkafka.com:9094}
    consumer:
      group-id: ${CLOUDKARAFKA_USERNAME:jip6qp3z}-consumers
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${CLOUDKARAFKA_USERNAME:jip6qp3z}" password="${CLOUDKARAFKA_PASSWORD:0Va4zYmZNNSD2HTNQy_qL7ajT2_D4MNe}";
    template:
      default-topic: ${CLOUDKARAFKA_USERNAME:jip6qp3z}
